# Generated by Django 6.1.1 on 2026-09-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('IN', 'In Progress'), ('COMPLETED', 'Completed')], default='IN', max_length=15),
        ),
    ]
