# Generated by Django 6.1.1 on 2026-09-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendance_first_half_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='early_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='flag_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_early',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='late_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='missing_punchout_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='first_half',
            field=models.CharField(blank=True, choices=[('PR', 'Present'), ('AB', 'Absent'), ('PT', 'PT')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='second_half',
            field=models.CharField(blank=True, choices=[('PR', 'Present'), ('AB', 'Absent'), ('PT', 'PT')], max_length=2, null=True),
        ),
    ]
