# Generated by Django 6.1.1 on 2026-09-05 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('crosses_midnight', models.BooleanField(default=False)),
                ('full_day_minutes', models.IntegerField(default=540)),
                ('half_day_minutes', models.IntegerField(default=270)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='attendance.shift')),
            ],
        ),
        migrations.CreateModel(
            name='PunchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punch_type', models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], max_length=3)),
                ('punch_timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punch_logs', to='attendance.employee')),
            ],
            options={
                'indexes': [models.Index(fields=['employee', 'punch_timestamp'], name='attendance__employe_db3692_idx')],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField()),
                ('punch_in_timestamp', models.DateTimeField(blank=True, null=True)),
                ('punch_out_timestamp', models.DateTimeField(blank=True, null=True)),
                ('first_half', models.CharField(blank=True, choices=[('PR', 'Present'), ('AB', 'Absent')], max_length=2, null=True)),
                ('second_half', models.CharField(blank=True, choices=[('PR', 'Present'), ('AB', 'Absent')], max_length=2, null=True)),
                ('total_worked_minutes', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('IN', 'In Progress'), ('COMPLETED', 'Completed')], default='IN', max_length=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='attendance.employee')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='attendance.shift')),
            ],
            options={
                'indexes': [models.Index(fields=['employee', 'attendance_date'], name='attendance__employe_37ed17_idx'), models.Index(fields=['attendance_date'], name='attendance__attenda_9d89bd_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'attendance_date'), name='uq_employee_attendance_date')],
            },
        ),
    ]
