# Generated by Django 6.1.1 on 2026-09-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='first_half',
            field=models.CharField(blank=True, choices=[('PR', 'Present'), ('AB', 'Absent'), ('PT', 'Pending')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='second_half',
            field=models.CharField(blank=True, choices=[('PR', 'Present'), ('AB', 'Absent'), ('PT', 'Pending')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('IN', 'In Progress'), ('COMPLETED', 'Completed'), ('AUTO_CLOSED', 'Auto Closed')], default='IN', max_length=15),
        ),
    ]
